[project]
name = "restaran-reserved"
version = "0.1.0"
description = ""
authors = [
    {name = "Elizaveta-14",email = "lizasalbanova@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "python-dotenv (>=1.1.1,<2.0.0)",
    "requests (>=2.32.4,<3.0.0)",
    "psycopg2-binary (>=2.9.10,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.lint.dependencies]
isort = "^6.0.1"
black = "^25.1.0"
flake8 = "^7.3.0"
mypy = "^1.17.1"


[tool.poetry.group.dev.dependencies]
pytest-cov = "^6.2.1"
black = "^25.1.0"

